name: Node Continuous Integration
on: push
jobs:
  build-container:
    name: Build Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  release-project:
    permissions: write-all
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-node
    steps:
      - uses: actions/download-artifact@v4.1.2
        with:
          name: static-site
      - run: ls -R
      - name: Archive Site content
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: site.zip
      - name: Create Github release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./site.zip
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: application/zip
  build-node:
    name: Build Node
    runs-on: ubuntu-latest
    container: node:20.2.0
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4.1.1
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: static-site
          path: .next/
